# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  xdcmd = {
    pname = "xdcmd";
    version = "ad6290abe1d73b280e8dccced26627b80a80c3cc";
    src = fetchgit {
      url = "https://github.com/TransparentLC/xdcmd.git";
      rev = "ad6290abe1d73b280e8dccced26627b80a80c3cc";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-xtAsPGwQ54jofDWVjC/RtLL59o/NDx7CcojoBmL1NBA=";
    };
    date = "2024-12-31";
  };
}
