name: build

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build-windows:
    runs-on: windows-latest
    env:
      PYTHONIOENCODING: utf-8
      PYTHONOPTIMIZE: 1
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
          cache: pip
          cache-dependency-path: requirements.txt
      - name: Setup MSVC
        uses: ilammy/msvc-dev-cmd@v1
      - name: Cache nuitka dependencies
        uses: actions/cache@v3
        with:
          path: ~/AppData/Local/Nuitka/Nuitka/Cache
          key: windows-nuitka
      - name: Install pip dependencies
        run: |
          pip install -U -r requirements.txt
          pip install -U nuitka zstandard ordered-set
      - name: Build executable
        run: |
          nuitka --standalone --onefile --assume-yes-for-downloads --output-filename=xdcmd main.py
      - name: Upload result
        uses: actions/upload-artifact@v3
        with:
          name: xdcmd
          path: xdcmd.exe
