name: build

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build-windows:
    runs-on: windows-latest
    env:
      PYTHONIOENCODING: utf-8
      PYTHONOPTIMIZE: 1
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: pip
          cache-dependency-path: requirements.txt
      - name: Setup MSVC
        uses: ilammy/msvc-dev-cmd@v1
      - name: Cache nuitka dependencies
        uses: actions/cache@v3
        with:
          path: ~/AppData/Local/Nuitka/Nuitka/Cache
          key: windows-nuitka
      - name: Install pip dependencies
        run: |
          pip install -U -r requirements.txt
          pip install -U nuitka zstandard ordered-set
      - name: Build executable
        run: |
          nuitka --standalone --assume-yes-for-downloads main.py
          mv main.dist/main.exe main.dist/xdcmd.exe
          rm main.dist/api-ms-win-*.dll
          rm main.dist/_bz2.pyd
          rm main.dist/_decimal.pyd
          rm main.dist/_elementtree.pyd
          rm main.dist/_hashlib.pyd
          rm main.dist/_lzma.pyd
          rm main.dist/_queue.pyd
          rm main.dist/_uuid.pyd
          rm main.dist/ucrtbase.dll
      - name: Upload result
        uses: actions/upload-artifact@v3
        with:
          if-no-files-found: error
          name: xdcmd-windows
          path: main.dist
      - name: Build executable (onefile)
        run: |
          nuitka --standalone --onefile --assume-yes-for-downloads --output-filename=xdcmd.exe main.py
      - name: Upload result (onefile)
        uses: actions/upload-artifact@v3
        with:
          if-no-files-found: error
          name: xdcmd-windows-onefile
          path: xdcmd.exe
